name: CursoSpigot
version: '${version}'
main: me.polvallverdu.cursospigot.CursoSpigot
api-version: '1.20'
author: Pol
website: polv.dev

depend:
  - ProtocolLib

commands:
  ejemplo:
    description: Comando para saludar
    aliases:
      - hola
    usage: "Usage: /ejemplo [nombre]"